const PROJECT_URL='https://aqanuwilmvdtlzuqlrau.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_-on9uPxVvSaERBEpkoc_xg_CYuANexJ';
const BUCKET='church-website-public-media';
const db=window.supabase.createClient(PROJECT_URL,PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const params=new URLSearchParams(location.search),church=params.get('church')||'M+';
const $=s=>document.querySelector(s),make=(tag,text='',className='')=>{const n=document.createElement(tag);n.textContent=text;n.className=className;return n;};
const dateLabel=value=>{const match=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return match?`${match[1]} 年 ${Number(match[2])} 月 ${Number(match[3])} 日`:'';};
function sectionShell(section,index){const article=make('section','','section bulletin-section');article.id=String(section.key||`section-${index}`).replace(/[^a-zA-Z0-9_-]/g,'-');article.dataset.section=section.key||'';const head=make('div','','section-head');head.append(make('span',iconFor(section.key),'section-icon'));const copy=make('div');copy.append(make('h2',section.title||'週報內容'),make('p',section.description||'','section-sub'));head.append(copy);article.append(head);return article;}
function iconFor(key){return ({program:'♪',news:'⌂',prayer:'♡',schedule:'✦',offering:'＋'})[key]||'✧';}
function appendItems(parent,items){let count=0;for(const item of items||[]){const label=String(item.label||'').trim(),body=String(item.body||'').trim();if(!label&&!body)continue;const card=make('article','','bulletin-entry-card');if(label)card.append(make('h3',label));if(body)card.append(make('p',body,'bulletin-copy'));parent.append(card);count++;}return count;}
function appendSchedule(parent,data,serviceDate){const roles=Array.isArray(data?.schedule_roles)?data.schedule_roles:[];const plusWeek=value=>{const m=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})/);if(!m)return '';const date=new Date(Number(m[1]),Number(m[2])-1,Number(m[3])+7,12);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;};const addWeek=(title,date,schedule)=>{const card=make('div',title==='下週服事'?'':'','duty'+(title==='下週服事'?' next':''));card.append(make('h3',`${title} · ${dateLabel(date)}`));if(!schedule){card.append(make('p','尚未建立這個日期的服事排班。','schedule-empty'));parent.append(card);return;}const dl=make('dl');let count=0;for(const role of roles){const value=String(schedule[role.role_key]||'').trim();if(!value||role.role_key==='event')continue;dl.append(make('dt',(role.icon?role.icon+' ':'')+(role.label||role.role_key)),make('dd',value));count++;}if(count)card.append(dl);else card.append(make('p','此日期的排班尚未填入服事人員。','schedule-empty'));parent.append(card);};const grid=make('div','','duty-grid');parent.append(grid);addWeek('本週服事',serviceDate,data?.schedule);addWeek('下週服事',plusWeek(serviceDate),data?.next_schedule);}
function render(bulletin,data){$('#bulletin-title').textContent=bulletin.title||'本週週報';$('#bulletin-subtitle').textContent=bulletin.subtitle||'';$('#bulletin-meta').textContent=[dateLabel(bulletin.service_date),bulletin.service_time].filter(Boolean).join('　·　');const imageBox=$('#bulletin-image');imageBox.replaceChildren();if(bulletin.hero_image_path){const image=document.createElement('img');image.className='bulletin-hero-image';image.alt='本週主日預告';image.loading='eager';image.src=db.storage.from(BUCKET).getPublicUrl(bulletin.hero_image_path).data.publicUrl;imageBox.append(image);}else{imageBox.append(make('div','M+ CHURCH · SUNDAY','bulletin-hero-placeholder'));}
  const content=$('#bulletin-content');content.replaceChildren();const sections=Array.isArray(bulletin.sections)?bulletin.sections:[];let rendered=0;
  sections.forEach((section,index)=>{if(section.enabled===false)return;const shell=sectionShell(section,index);if(section.auto_schedule||section.key==='schedule')appendSchedule(shell,data,bulletin.service_date);else appendItems(shell,section.items);if(!shell.querySelector('.bulletin-entry-card,.duty-grid,.schedule-empty'))return;content.append(shell);rendered++;});
  if(!rendered)content.append(make('div','這份週報目前尚未填入對外發布的內容。','bulletin-empty'));
  content.append(make('p','服事人員依教會排班系統中相同日期的資料自動顯示。','bulletin-source-note'));
}
function showError(){const content=$('#bulletin-content');content.replaceChildren();const box=make('section','','bulletin-empty');box.append(make('h2','本週週報正在準備中'),make('p','目前沒有已發布的週報，請稍後再來看看。'));content.append(box);}
async function start(){if(!['M+','SHiNE'].includes(church)){showError();return;}try{const {data,error}=await db.rpc('get_website_weekly_data',{p_church:church,p_service_date:null});if(error||!data?.bulletin){showError();return;}render(data.bulletin,data);}catch{showError();}}
start();
